#!/usr/bin/env bash

USAGE="$(basename "$0") [-a] [-g] user -- Find the email address of any GitHub user

where:
    -a display all possible email adddresses
    -g only display matches that relate to a user's Gravatar ID"

if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ -z "$1" ] ; then
  echo "$USAGE"
  exit
fi

if [ "$1" == "-a" ] || [ "$1" == "-g" ] ; then
  if [ -z "$2" ] ; then
    echo "$USAGE"
    exit
  fi

  USER=$2
  RESPONSE=`curl -s https://api.github.com/users/$2/events/public`
  EMAILS=`echo "$RESPONSE" | grep "\"email\":" | sed -e's/[,|"]//g' | sort | uniq -c | sort -n | awk '{print $(NF)}' | grep -v null`
  
  if [ "$1" == "-g" ] ; then
    GID=`echo "$RESPONSE" | grep "\"gravatar_id\":" | sed -e's/[,|"]//g' | head -n 1 | awk '{print $(NF)}'`
    for EMAIL in $EMAILS ; do
      if [ $GID == `md5 -q -s $EMAIL` ] ; then
        echo "$EMAIL"
      fi
    done
  else
    echo "$EMAILS"
  fi
  exit
fi

USER=$1
FILTER='tail -n1'
RESPONSE=`curl -s https://api.github.com/users/$USER`
EMAIL=`echo "$RESPONSE" | grep "\"email\":" | sed -e's/[,|"]//g' | awk '{print $(NF)}' | grep -v null`

if [ -z "$EMAIL" ] ; then
  EMAIL=`curl -s https://api.github.com/users/$USER/events/public | grep "\"email\":" | sed -e's/[,|"]//g' | sort | uniq -c | sort -n | awk '{print $(NF)}' | grep -v null | tail -n1`
fi

echo "$EMAIL"
