#!/usr/bin/env bash

usage="$(basename "$0") [-a] user -- Find the email address of any GitHub user

where:
    -a display all possible email adddresses"

if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "" ] || [ "$1" == "-a" ] && [ "$2" == "" ]; then
  echo "$usage"
  exit
fi

if [ "$1" == "-a" ] ; then
  USER=$2
  FILTER='cat -'
else
  USER=$1
  FILTER='tail -n1'
fi

curl -s https://api.github.com/users/$USER/events/public | grep "\"email\":" | sed -e's/[,|"]//g' | sort | uniq -c | sort -n | awk '{print $(NF)}' | grep -v null | $FILTER
